const data = {
  products: [
    {
      name: 'Black pant',
      slug: 'black-pant',
      catagory: 'pants',
      image: '/images/pants1.jpg',
      price: 600,
      brand: 'Max',
      rating: 4,
      numReviews: 8,
      countInStock: 15,
      description: 'A black formal pant',
    },
    {
      name: 'Gray Pant',
      slug: 'gray-pant',
      catagory: 'pants',
      image: '/images/pants2.jpg',
      price: 850,
      brand: 'Max',
      rating: 5,
      numReviews: 9,
      countInStock: 10,
      description: 'A dark gray formal pant',
    },
    {
      name: 'White Pant',
      slug: 'white-pant',
      catagory: 'pants',
      image: '/images/pants3.jpg',
      price: 700,
      brand: 'Max',
      rating: 5,
      numReviews: 10,
      countInStock: 10,
      description: 'A white casual pant',
    },
    {
      name: 'Casual Shirt',
      slug: 'casual-shirt',
      catagory: 'shirts',
      image: '/images/shirt1.jpg',
      price: 800,
      brand: 'Max',
      rating: 4,
      numReviews: 7.5,
      countInStock: 20,
      description: 'Multi color casual wear shirt',
    },
    {
      name: 'Pink Shirt',
      slug: 'pink-shirt',
      catagory: 'shirts',
      image: '/images/shirt2.jpg',
      price: 950,
      brand: 'Max',
      rating: 4,
      numReviews: 9,
      countInStock: 12,
      description: 'Official formal wear',
    },
    {
      name: 'Blue Shirt',
      slug: 'blue-shirt',
      catagory: 'shirts',
      image: '/images/shirt3.jpg',
      price: 1500,
      brand: 'Max',
      rating: 5,
      numReviews: 10,
      countInStock: 10,
      description: 'Official formal light shade wear',
    },
  ],
};

export default data;
